-- Insert sample data into the partner table

INSERT INTO partner (organization_name, type, contact_email, contact_phone, contact_url, logo_path, description, created_at) VALUES
('Healthify Inc', 'Healthcare', 'contact@healthify.com', '123-456-7890', 'http://www.healthify.com','health-tech.png', 'Dedicated to improving health services.', CURRENT_TIMESTAMP),
('TechGuru', 'Technology', 'info@techguru.com', '123-456-7891', 'http://www.techguru.com', 'info-tech.png', 'Leading tech news and services provider.', CURRENT_TIMESTAMP),
('GreenEarth', 'Environment', 'support@greenearth.com', '123-456-7892', 'http://www.greenearth.com', 'green-tech.png' , 'Focused on environmental awareness and activism.', CURRENT_TIMESTAMP),
('GameZone', 'Entertainment', 'hello@gamezone.com', '123-456-7893', 'http://www.gamezone.com','game-tech.png', 'The ultimate place for gamers.', CURRENT_TIMESTAMP),
('FoodWonders', 'Food Service', 'contact@foodwonders.com', '123-456-7894', 'http://www.foodwonders.com', 'food-tech.png', 'Delivering delicious food everywhere.', CURRENT_TIMESTAMP),
('StudyBuddy', 'Education', 'info@studybuddy.com', '123-456-7895', 'http://www.studybuddy.com', 'study-tech.png','Assisting students in learning and development.', CURRENT_TIMESTAMP),
('ShopSmart', 'Retail', 'support@shopsmart.com', '123-456-7896', 'http://www.shopsmart.com', 'fin-tech.png','Your smart shopping partner.', CURRENT_TIMESTAMP),
('CareersNow', 'Career Services', 'hello@careersnow.com', '123-456-7897', 'http://www.careersnow.com', 'up-tech.png','Helping you find the right career path.', CURRENT_TIMESTAMP),
('ArtistsHub', 'Art', 'contact@artistshub.com', '123-456-7898', 'http://www.artistshub.com', 'prod-tech.png', 'Connecting artists around the world.', CURRENT_TIMESTAMP),
('FitnessPro', 'Fitness', 'info@fitnesspro.com', '123-456-7899', 'http://www.fitnesspro.com', 'medical-tech.png','Dedicated to your fitness journey.', CURRENT_TIMESTAMP),
('HealthCheck','NGO','healthcheck@gmail.com','234-232-2342','www.healthcheck.com','health-tech.png','Check your health for any problems with health check', CURRENT_TIMESTAMP),
('Zingers Chicken Restaurant' ,'Corperation','zingerchkn@gmail.com','123-412-2344','www.zinger-wings.com','flash-tech.png','Serving up quality chicken sandwiches to feed the staff and students.', CURRENT_TIMESTAMP),
('Stationery Shop','Private','stationeryshop@gmail.com','345-345-4564','www.stationery.com','study-tech.png','Buy your school supplies here!',CURRENT_TIMESTAMP),
('Team Plants','NGO','teamplants@gmail.com','465-654-5768','www.teamplants.com','green-tech.png','Help save the Earth by buying a plant!',CURRENT_TIMESTAMP),
('Book Club','Corperation','bkclub@gmail.com','534-564-6857','www.bookclub.com','reading-tech.png','Dive into the world of literature with book club.',CURRENT_TIMESTAMP),
('Business Leaders','Private','bznessleads@gmail.com','213-423-5467','www.business.com','fin-tech.png','Interested in business? Look no further with business leaders club',CURRENT_TIMESTAMP),
('ComputerBuy','NGO','compbuy@gmail.com','768-879-6789','www.com-buy.com','computer-tech.png','Interested in buying a computer? Our site has used and new just for you!', CURRENT_TIMESTAMP),
('TeenageCoding','Corperation','teenscode@gmail.com','456-345-5679','www.tn-code.com','info-tech.png','Are you a teen interested in learning to code, we offer lessons in a variety of languages designed just for you!', CURRENT_TIMESTAMP),
('GameProgramming','Private','gameprogramming@gmail.com','909-788-9890','www.gaming.com','game-tech.png','Want to program a game instead of play one?', CURRENT_TIMESTAMP),
('CleanEarth Volunteering','NGO','clnearth@gmail.com','845-845-4568','www.clean-earth.com','recycle-tech.png','Clean Earth Organization is a global non-profit dedicated to promoting environmental sustainability and reducing pollution through community-driven initiatives and education.', CURRENT_TIMESTAMP),
('Teachers Council','Corperation','teachcouncil@gmail.com','909-934-2343','www.teacher-council.com','wise-tech.png','Are you a teacher looking to discuss classwork and lesson plans? Find other teachers to talk to!', CURRENT_TIMESTAMP),
('Investing Simulator 3','NGO','investisimulator@gmail.com','657-485-4565','www.invest.com','fin-tech.png','A fun investing game that teaches real world stock investing on a free simulator.', CURRENT_TIMESTAMP),
('3D Prints','NGO','threedprints@gmail.com','124-234-6534','www.3dp.com','prod-tech.png','Interested into 3D printing? ', CURRENT_TIMESTAMP),
('Food Community','Corperation','foodcom@gmail.com','789-908-7965','www.food.com','food-tech.png','Each year our school donates to the local food bank', CURRENT_TIMESTAMP),
('Health Canada','Private','healthcanada@gmail.com','487-567-8679','www.health.ca','medical-tech.png','Keep your health in check using health canada', CURRENT_TIMESTAMP),
('Career Club','NGO','careersclub@gmail.com','435-765-6786','www.career.com','up-tech.png', 'Career Club is a initiative designed to assist individuals in exploring and advancing their careers through a comprehensive range of resources, guidance, and job opportunities across various industries in Canada. Talk to others pursuing similar interests in this club', CURRENT_TIMESTAMP),
('TechKids','Corperation','techkids@gmail.com','345-456-5676','www.kids.tech','study-tech.png','Tech Kids is an innovative collaboration between schools and technology companies, aimed at educating and inspiring young students in the field of technology through hands-on learning and mentorship.', CURRENT_TIMESTAMP),
('ScienceHUB','NGO','sciencehub@gmail.com','234-292-3494','www.sci-hub.com','info-tech.png','Learn Chemistry, Biology, Physics and everything else with ScienceHUB', CURRENT_TIMESTAMP),
('Modern Design Association','NGO','modesign@gmail.com','456-348-3956','www.design.com','prod-tech.png','Want to design something? Heres a 3D modelling software to do so', CURRENT_TIMESTAMP),
('ABC Math Tutoring','Corperation','abcmath@gmail.com','586-923-3494','www.math.info','up-tech.png','Struggling with math? Find tutors near you to help.', CURRENT_TIMESTAMP),
('iteems','Private','iteens@gmail.com','405-390-4039','www.iteems.com','study-tech.png','IT internship for teenagers', CURRENT_TIMESTAMP),
('AI for Youth','NGO','aiyouth@gmail.com','340-293-4303','www.ai-youth.com','computer-tech.png','Learn how to use AI for youth', CURRENT_TIMESTAMP),
('Donation Bank','Corperation','donationbank@gmail.com','343-940-9405','www.don-bank.com','fin-tech.png','Tech and Career funding', CURRENT_TIMESTAMP),
('StudentHelp','Private','studenthelp@gmail.com','780-504-3493','www.study-help.com','study-tech.png','Intern as a TA for Tech courses', CURRENT_TIMESTAMP),
('Learn2Code','Corperation','learntocode@gmail.com','495-964-2932','www.learn-code.com','info-tech.png','Coding internship for teaching', CURRENT_TIMESTAMP);


